"""create diseases and cases tables

Revision ID: 4f931cec4aae
Revises: 863f57021fa6
Create Date: 2026-07-09 18:42:36.161086
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4f931cec4aae"
down_revision: str | None = "863f57021fa6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diseases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum("HEMATOLOGY", "CHEMISTRY", "MICROBIOLOGY", "PARASITOLOGY", name="disease_category"),
            nullable=False,
        ),
        sa.Column(
            "symptom_template",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "lab_pattern_template",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "difficulty_levels",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_diseases_category"), "diseases", ["category"], unique=False)
    op.create_index(op.f("ix_diseases_name"), "diseases", ["name"], unique=True)
    op.create_table(
        "cases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_pseudo_id", sa.String(length=32), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("sex", sa.Enum("MALE", "FEMALE", name="patient_sex"), nullable=False),
        sa.Column("clinical_history", sa.Text(), nullable=False),
        sa.Column(
            "doctor_request",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("disease_id", sa.UUID(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("NOVICE", "INTERMEDIATE", "ADVANCED", name="difficulty_level"),
            nullable=False,
        ),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column(
            "generated_by",
            sa.Enum("SYSTEM", "LECTURER", name="case_generated_by"),
            nullable=False,
        ),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["disease_id"], ["diseases.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requested_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_disease_id"), "cases", ["disease_id"], unique=False)
    op.create_index(
        op.f("ix_cases_patient_pseudo_id"), "cases", ["patient_pseudo_id"], unique=False
    )
    op.create_index(
        op.f("ix_cases_requested_by_id"), "cases", ["requested_by_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_requested_by_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_patient_pseudo_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_disease_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_diseases_name"), table_name="diseases")
    op.drop_index(op.f("ix_diseases_category"), table_name="diseases")
    op.drop_table("diseases")
    # ### end Alembic commands ###

    # Postgres ENUM types created by sa.Enum(...) are not dropped by
    # drop_table automatically — remove them explicitly so upgrade/downgrade
    # is fully reversible (re-running upgrade after downgrade must not hit
    # "type already exists").
    bind = op.get_bind()
    sa.Enum(name="case_generated_by").drop(bind, checkfirst=True)
    sa.Enum(name="difficulty_level").drop(bind, checkfirst=True)
    sa.Enum(name="patient_sex").drop(bind, checkfirst=True)
    sa.Enum(name="disease_category").drop(bind, checkfirst=True)
